discogs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', include('website.urls')),
    # url(r'^blog/', include('blog.urls')),
    url(r'^home/', include('website.urls', namespace='website', app_name='website')),
    url(r'^admin/', include(admin.site.urls)),
   	url('', include('social.apps.django_app.urls', namespace='social')),
)

website/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('website.views',
    # Examples:
    # url(r'^$', 'discogs.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'index',name="index"),
    url(r'^addTag/$', 'addTag',name="addTag"),
    url(r'^upvoteTag/$', 'upvoteTag',name="upvoteTag"),
    url(r'^downvoteTag/$', 'downvoteTag',name="downvoteTag"),
    url(r'^login/$', 'login',name="login"),
    url(r'^search/$', 'search', name="search"),
    url(r'^playlists/$', 'getplaylists', name="getplaylists"),
    url(r'^getreleaseids/$', 'getreleaseids', name="getreleaseids"),
    url(r'^recommend/$', 'recommend', name="recommend"),
    url(r'^searchall/$', 'searchall', name="searchall"),
    url(r'^getstyles/$', 'getstyles', name="getstyles"),
    url(r'^styleclick/$', 'styleclick', name="styleclick"),
    url(r'^logout/$', 'logout', name="logout"),
    url(r'^more/$', 'more', name="more"),
    url(r'^save/$', 'save', name="save"),
    url(r'^release/(?P<release_id>[0-9]+)/$', 'release', name="release"),
    url(r'^tag/(?P<tag_id>[0-9]+(,[0-9]+)*)/$', 'tag', name="tags"),
    url(r'^country/(?P<country>[a-zA-Z]+)/$', 'Country', name="Country"),
    url(r'^searchartist/(?P<artist>[a-zA-Z]+)/$', 'searchartist', name="searchartist"),
    url(r'^artist/(?P<artist_id>[0-9]+(,[0-9]+)*)/$', 'artist', name="artist"),
)

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render
from django.template import RequestContext, loader
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout as auth_logout, login
from django.db import connection, transaction
from django.core import serializers
import json
import decimal
import re
from random import randint
import random
#from django.utils import simplejson


import MySQLdb as mdb

from social.backends.oauth import BaseOAuth1, BaseOAuth2
from social.backends.google import GooglePlusAuth
from social.backends.utils import load_backends
from social.apps.django_app.utils import psa
from operator import itemgetter

def index(request):
    return render(request, 'website/index.html')

def searchall(request):
    isJson = request.GET.get('json', '')
    query = request.GET['q']
    query = query.replace(" ", "&")
    print query
    nextoffset = 0
    previousoffset = 0
    limit = 10
    try:
        nextoffset = int(request.GET['offset'])
    except Exception as e:
        nextoffset = 0
    try:
        limit = int(request.GET['limit'])
    except Exception as e:
        limit = 10
    cursor = connection.cursor()
    #cursor.execute("select * from release where to_tsvector('english', title) @@ plainto_tsquery('english',%s) order by title limit %s offset %s", [query, limit, nextoffset])
    #q = "select * from release where id in (select release_id from releases_artists where to_tsvector('english', artist_name) @@ plainto_tsquery('english', %s ) UNION select release.id from release where to_tsvector('english', title) @@ plainto_tsquery('english', %s) UNION select release.id from release where to_tsvector('english', styles) @@ plainto_tsquery('english', %s ) UNION select release.id from release where to_tsvector('english', genres) @@ plainto_tsquery('english',%s) limit 150)"
    #cursor.execute("select * from release where id in (select release_id from releases_artists where to_tsvector('english', artist_name) @@ plainto_tsquery('english', %s ) UNION select release.id from release where to_tsvector('english', title) @@ plainto_tsquery('english', %s) UNION select release.id from release where to_tsvector('english', styles) @@ plainto_tsquery('english', %s ) UNION select release.id from release where to_tsvector('english', genres) @@ plainto_tsquery('english',%s) limit 150)", [query, query, query, query])
    '''
    select * from (select distinct on (r.title) * from (
    (select * from
            (select  r.*, y.views as views
             from release r join releases_artists a on r.id=a.release_id join releases_youtube y on a.release_id = y.release_id
             where to_tsvector('english', a.artist_name) @@ plainto_tsquery('english', %s)
             order by y.views desc) as k)
    UNION
        (select * from
            (select a.*, y.views as views
            from release a join releases_youtube y on a.id = y.release_id
            where to_tsvector('english', a.title) @@ plainto_tsquery('english', %s)
            order by y.views desc) as k1)
    UNION
        (select * from
            (select a.*, y.views as views
            from release a join releases_youtube y on a.id = y.release_id
            where to_tsvector('english', a.styles) @@ plainto_tsquery('english', %s)
            order by y.views desc) as k2)
    UNION
        (select * from
            (select a.*, y.views as views
            from release a join releases_youtube y on a.id = y.release_id
            where to_tsvector('english', a.genres) @@ plainto_tsquery('english', %s)
            order by y.views desc) as k3)
    ) as r) as k order by k.views desc

    '''
    # cursor.execute("select * from (select distinct on (r.title) * from (" +
    # " (select * from (select  r.*, y.views as views, y.youtube_id from release r join releases_artists a on r.id=a.release_id" +
    # " join releases_youtube y on a.release_id = y.release_id" +
    # " where to_tsvector('english', a.artist_name) @@ plainto_tsquery('english', %s)" +
    # " order by y.views desc) as k)" +
    # " UNION (select * from (select a.*, y.views as views, y.youtube_id"
    # " from release a join releases_youtube y on a.id = y.release_id"
    # " where to_tsvector('english', a.title) @@ plainto_tsquery('english', %s)"
    # " order by y.views desc) as k1)"
    # " UNION (select * from (select a.*, y.views as views, y.youtube_id"
    # " from release a join releases_youtube y on a.id = y.release_id"
    # " where to_tsvector('english', a.styles) @@ plainto_tsquery('english', %s)"
    # " order by y.views desc) as k2)"
    # " UNION (select * from (select a.*, y.views as views, y.youtube_id"
    # " from release a join releases_youtube y on a.id = y.release_id"
    # " where to_tsvector('english', a.genres) @@ plainto_tsquery('english', %s)"
    # " order by y.views desc) as k3)) as r) as k order by k.views desc limit 50", [query, query, query, query])
    randomInt = random.randint(1,5624375)
    #query = "select * from (select distinct on (rid) r.id as rid, views from release r join releases_artists a on r.id = a.release_id join releases_youtube y on a.release_id = y.release_id join releases_labels l on y.release_id = l.release_id where " + artist + " and " + style + " and " + genre + " and " + country + " and " + time + " and " + label + " and a.release_id <> " + release_id + " order by rid) as b where b.rid>random()*" + str(randomInt) + " limit 100"

    cursor.execute("select * from (select distinct on (r.title) * from (" +
    " (select * from (select  r.*, y.views as views, y.youtube_id from release r join releases_artists a on r.id=a.release_id" +
    " join releases_youtube y on a.release_id = y.release_id" +
    " where to_tsvector('english', a.artist_name) @@ plainto_tsquery('english', %s)" +
    " order by y.views desc) as k4)" +
    " UNION (select * from (select a.*, y.views as views, y.youtube_id"
    " from release a join releases_youtube y on a.id = y.release_id"
    " where to_tsvector('english', a.title) @@ plainto_tsquery('english', %s)"
    " order by y.views desc) as k1)"
    " UNION (select * from (select a.*, y.views as views, y.youtube_id"
    " from release a join releases_youtube y on a.id = y.release_id"
    " where to_tsvector('english', a.styles) @@ plainto_tsquery('english', %s)"
    " ) as k2)"
    " UNION (select * from (select a.*, y.views as views, y.youtube_id"
    " from release a join releases_youtube y on a.id = y.release_id"
    " where to_tsvector('english', a.genres) @@ plainto_tsquery('english', %s)"
    " ) as k3)"
    " UNION (select * from (select a.*, y.views as views, y.youtube_id"
    " from release a join releases_youtube y on a.id = y.release_id"
    " where to_tsvector('english', y.title) @@ plainto_tsquery('english', %s)"
    " ) as k4)) as r) as k order by k.views desc", [query, query, query, query, query])

    rows = cursor.fetchall()
    #cursor.execute("select count(*) from release where to_tsvector('english', title) @@ plainto_tsquery('english',%s)", [query])
    #row = cursor.fetchone()
    releases = []
    for r in rows:
        releases.append(r)
    #releases_json = json.dumps(releases)
    releases_json = releases
    # if nextoffset+10 >= row[0]:
    #     if nextoffset == 0:
    #         previousoffset = nextoffset
    #         nextoffset = nextoffset
    #     else:
    #         previousoffset = nextoffset - 10
    #         nextoffset = nextoffset
    # else:
    #     if nextoffset == 0:
    #         previousoffset = 0
    #     else:
    #         previousoffset = nextoffset - 10
    #     nextoffset = nextoffset + 10
    # c = {
    #         'query':query,
    #         'rows': rows,
    #         'offset':nextoffset,
    #         'previousoffset':previousoffset,
    #         'limit': limit,
    #     }
    all_info = json.dumps({'releases':releases_json,
                            'offset':nextoffset,
                            'previousoffset':previousoffset,
                            'limit':limit,
                            'query':query,
                            })
    # if isJson == '':
    #     return render(request, 'website/search.html', c)
    # else:
    return HttpResponse(all_info)

def search(request):
    isJson = request.GET.get('json', '')
    query = request.GET['q']
    nextoffset = 0
    previousoffset = 0
    try:
        nextoffset = int(request.GET['offset'])
    except Exception as e:
        nextoffset = 0
    #con = mdb.connect('50.74.234.98', 'discogs', 'discogs', 'discogs');
    cursor = connection.cursor()
    cursor.execute("select * from release where to_tsvector('english', title) @@ plainto_tsquery('english',%s) order by title limit 10 offset %s", [query , nextoffset])
    rows = cursor.fetchall()
    cursor.execute("select count(*) from release where to_tsvector('english', title) @@ plainto_tsquery('english',%s)", [query])
    row = cursor.fetchone()
    releases = []
    for r in rows:
        releases.append(r)
    #releases_json = json.dumps(releases)
    releases_json = releases
    if nextoffset+10 >= row[0]:
        if nextoffset == 0:
            previousoffset = nextoffset
            nextoffset = nextoffset
        else:
            previousoffset = nextoffset - 10
            nextoffset = nextoffset
    else:
        if nextoffset == 0:
            previousoffset = 0
        else:
            previousoffset = nextoffset - 10
        nextoffset = nextoffset + 10
    c = {
            'query':query,
            'rows': rows,
            'offset':nextoffset,
            'previousoffset':previousoffset,
        }
    all_info = json.dumps({'releases':releases_json,
                            'offset':nextoffset,
                            'previousoffset':previousoffset,
                            'query':query,
                            })
    if isJson == '':
        return render(request, 'website/search.html', c)
    else:
        return HttpResponse(all_info)

def release(request, release_id):

templates/website/base.html
<!DOCTYPE html>
<html lang="en">
 <head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>{% block title %}Discogs Tags{% endblock %}</title>

   <!-- Bootstrap -->
   <!--<link href="/static/css/bootstrap.min.css" rel="stylesheet">-->
   <!--<link href="/static/css/bootstrap-theme.min.css" rel="stylesheet">-->
   <!--<link href="/static/css/fbposter.css" rel="stylesheet">-->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Optional theme -->
   <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">-->

    <!-- Latest compiled and minified JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/4.2.1/bootstrap-social.css">

   <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
   <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
   <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
     <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
   <![endif]-->
 </head>
 <body>
  <nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Discogs Tags</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
        {% if user and not user.is_anonymous %}
        <p class="navbar-text">Signed in as {{ user.get_full_name|default:user.username }}</p>
        {%endif%}
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search" method="get" action="{%url 'website:search'%}">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="q">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <li>
        {% if user and not user.is_anonymous %}
        <form action="{%url 'website:logout'%}">
          <button type="submit" class="btn btn-default navbar-btn"> Logout</button>
        </form>
        {%endif%}
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- Page Content -->
<div class="container">
  {% if user and not user.is_anonymous %}

  {% block container %}  {% endblock %}

  {% else %}
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 jumbotron">
      <div class="row">
        <div class="col-xs-12">
          <h2 class="text-center">Login</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6 col-xs-offset-3 top-buffer">
          <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}" class="btn btn-block btn-social btn-facebook"> <i class="fa fa-facebook"></i>Login with Facebook</a>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6 col-xs-offset-3 top-buffer">
          <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}" class="btn btn-block btn-social btn-google-plus"><i class="fa fa-google-plus"></i>Login with Google</a>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6 col-xs-offset-3 top-buffer">
          <a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}" class="btn btn-block btn-social btn-twitter"><i class="fa fa-twitter"></i>Login with Twitter</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  <!-- Page Heading -->
  <!--<div class="row">-->
  <!--<div class="col-lg-12">-->
  <!--<h2 class="page-header text-center">Popular Tags</h2>-->
  <!--</div>-->
  <!--</div>-->
  <!-- /.row -->
</div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy;</p>
      </div>
    </div>
    <!-- /.row -->
  </footer>
   <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

  {% block script %}  {% endblock %}
   <!-- Include all compiled plugins (below), or include individual files as needed -->
   <!--<script src="/static/js/bootstrap.min.js"></script>-->
	<style>
		.top-buffer { margin-top:20px; }
			</style>
 </body>
</html>

templates/website/country.html
{% extends 'website/base.html' %}

{% load url from future %}

{% block container %}

	{%for row in rows%}
	<!--a href = "/home/release/{{row.0}}"-->
		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3><a href="/home/release/{{row.0}}">{{row.2}}</a><small class="text-right pull-right">{{row.4}}</small></h3>
						<a href="/home/country/{{row.3}}"><p class="lead" style="color:#949494">{{row.3}}</p></a>
					</div>
				</div>
			</div>
		</div>
	<!--/a-->
	{%endfor%}
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<nav>
				<ul class="pager">
					<li class="previous"><a href="{%url 'website:search'%}?q={{query}}&offset={{previousoffset}}">Previous</a></li>
					<li class="next"><a href="{%url 'website:search'%}?q={{query}}&offset={{offset}}">Next</a></li>
				</ul>
			</nav>
		</div>
	</div>
	{{count}}

{% endblock %}

templates/website/index.html
{% extends 'website/base.html' %}

{% load url from future %}

{% block container %}
{% endblock %}

templates/website/release.html
{% extends 'website/base.html' %}

{% block script %}

<script>
function listGenres(){
	//var list = {{r.7}};
	//return list;
}
function addTag(){
	var tag = $("#tagField").val();
	$.ajax({
				url: "{% url 'website:addTag'%}",
				data: {"tag": tag, "release": {{query}}},
				success: function(result){
					console.log(result);
					location.reload();
				}
	});
}

function upvoteTag(tagid){
	$.ajax({
				url: "{% url 'website:upvoteTag'%}",
				data: {"tagid": tagid, "release": {{query}}},
				success: function(result){
					console.log(result);
					location.reload();
				}
	});
}

function downvoteTag(tagid){
	$.ajax({
				url: "{% url 'website:downvoteTag'%}",
				data: {"tagid": tagid, "release": {{query}}},
				success: function(result){
					console.log(result);
					location.reload();
				}
	});
}

function explore(){
	var names = [];
	$('input:checked').each(function() {
		names.push($(this).attr("value"));
	});
	window.location.href = '/home/tag/' + names;
}

</script>

{% endblock %}

{% block container %}
<div class="row">
	<div class="col-xs-8">
		<div class="panel panel-default">
			<div class="panel-body">
				{%for r in row1%}
				<div id='title'><strong><h3>Album Title: {{r.2}}</h3></strong></div>
				<div id='country'><strong><h5>Country: {{r.3}}</h5></strong></div>
				<div id='released'><strong><h5>Release Date: {{r.4}}</h5></strong></div>
				<div id='notes'><strong><h5>Notes: {{r.6}}</h5></strong></div>
				<div id='genres'><strong><h5>Genres: {{r.7}}</h5></strong></div>
				<div id='styles'><strong><h5>Styles: {{r.8}}</h5></strong></div>
				{%endfor%}
				{%for r in row2%}
				<div id='artist'><h5>Artist: <a href="/home/searchartist/{{r.3}}">{{r.3}}</a></h5></div>
				{%endfor%}
				{%for r in row3%}
				<div id='label'><h5>Label Text: {{r.0}}</h5></div>
				<div id='catno'><h5>Cat#: {{r.2}}</h5></div>
				<div id="tracks"><h5>Tracks: </h5></div>
				{%endfor%}
				{% for track in tracks%}
					<div id="{{track.2}}">{{track.3}} <small>{{track.4}}</small></div>
				{%endfor%}
				<br>
				<h4>Spotify Info</h4>
				{% if not row4 %}
				Information not available
				{% else %}
				{%for r in row4%}
				<!--<iframe src="https://embed.spotify.com/?uri=spotify%3Atrack%A{{r.1}}" width="300" height="80" frameborder="0" allowtransparency="true"></iframe>-->
				<!--div id='spotifyalbum'><h5><a href="https://open.spotify.com/album/{{r.1}}">Album Link</a></h5></div>
				<div id='spotifytrack'><h5><a href="https://open.spotify.com/track/{{r.4}}">Song Link</a></h5></div>-->

				<iframe src="https://embed.spotify.com/?uri=spotify:album:{{r.1}}" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
				{%endfor%}
				{%endif%}
				<br>
				<h4>Youtube Info</h4>
				{%for r in row5%}
					<iframe width="240" height="180" src="http://www.youtube.com/embed/{{r.1}}"></iframe>
					<!--div id='youtubetitle'><h5>Title: {{r.3}}</h5></div>
					<div id='youtubedescription'><h5>Description: {{r.4}}</h5></div>
					<div id='videoduration'><h5>Duration: {{r.5}} seconds</h5></div>
					<div id='Views'><h5>Views: {{r.4}}</h5></div>
					<div id='Rating'>Rating: {{r.7}}</div -->
				{%endfor%}
			</div>
		</div>
	</div>
	<div class="col-xs-4">
		<div class="panel panel-default">
			<div class="panel-body">
				<h3>
					Tags
					<button type="button" class="btn btn-default pull-right" aria-label="Left Align" data-toggle="modal" data-target="#addTagModal">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					</button>
				</h3>
				{%for tag in tags%}
					<div class="row">
						<div class="col-xs-10">
							<div class="panel panel-default" style="border-radius: 0;">
								<div class="panel-body">
									<a href="#" onclick="upvoteTag({{tag.0}});return false;"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true" style="float:left; width:15%; text-align:left;height:100%;color:green"> {{tag.2}}</span></a>
									<span style="float:left; width:70%; text-align:center;"><a href="/home/tag/{{tag.0}}" class="text-center">{{tag.1}}</a></span>
									<a href="#" onclick="downvoteTag({{tag.0}});return false;"><span class="glyphicon glyphicon-thumbs-down" aria-hidden="true" style="float:left; width:15%; text-align:right;height:100%;color:red"> {{tag.3}} </span></a>
								</div>
							</div>
						</div>
						<div class="col-xs-2">
							<div class="panel panel-default" style="border-radius: 0;border:0;box-shadow:0 0 0 0">
								<div class="panel-body" style="border:0">
									<input class="tag" type="checkbox" value="{{tag.0}}">
								</div>
							</div>
						</div>
					</div>
				{%endfor%}
				<button type="button" onclick="explore()" class="btn btn-primary pull-right">Explore</button>

			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="addTagModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Add Tag</h4>
			</div>
			<div class="modal-body">
				<div class="form-inline text-center">
					<div class="form-group">
						<input class="form-control" id="tagField" placeholder="Tag" name="tag">
					</div>
					<a href="#" type="submit" class="btn btn-default" onclick="addTag();return false;">Save</a>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>



{% endblock %}

templates/website/search.html
{% extends 'website/base.html' %}

{% load url from future %}

{% block container %}


	{%for row in rows%}
	<!--a href = "/home/release/{{row.0}}"-->
		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3><a href="/home/release/{{row.0}}">{{row.2}}</a><small class="text-right pull-right">{{row.4}}</small></h3>
						<a href="/home/country/{{row.3}}" class="lead" style="color:#949494">{{row.3}}</a>
					</div>
				</div>
			</div>
		</div>
	<!--/a-->
	{%endfor%}
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<nav>
				<ul class="pager">
					<li class="previous"><a href="{%url 'website:search'%}?q={{query}}&offset={{previousoffset}}">Previous</a></li>
					<li class="next"><a href="{%url 'website:search'%}?q={{query}}&offset={{offset}}">Next</a></li>
				</ul>
			</nav>
		</div>
	</div>
	{{count}}

{% endblock %}

templates/website/tags.html
{% extends 'website/base.html' %}

{% load url from future %}

{% block container %}

	{%for row in row1%}
	<a href = "/home/release/{{row.0}}">
		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3><a href="/home/release/{{row.0}}">{{row.2}}</a><small class="text-right pull-right">{{row.4}}</small></h3>
						<a href="/home/country/{{row.3}}" class="lead" style="color:#949494">{{row.3}}</a>
					</div>
				</div>
			</div>
		</div>
	</a>
	{%endfor%}
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<nav>
				<ul class="pager">
					<li class="previous"><a href="\home\tag\{{query}}?offset={{previousoffset}}">Previous</a></li>
					<li class="next"><a href="\home\tag\{{query}}?offset={{offset}}">Next</a></li>
				</ul>
			</nav>
		</div>
	</div>
	{{count}}

{% endblock %}